### ISSUE TITLE
rebase not mentioned

### ISSUE THREAD

**Issue by gotcha** [git/git-reference#1]
As a lot of users do switch from svn and need to keep working with svn. Helping them to do it with the git client seems useful.

If this is a wrong statement from a git newbie, I am happy to be told so.

**Comment by schacon** [comment]
keeping it simple.  you don't really need to use rebase - many people don't.

**Comment by gotcha** [comment]
I understand rebase is not needed when using git ONLY.

However, some of the switchers (like me) do wish to use git to manage code that still needs to sit in shared svn repositories.

My current understanding is that rebase is then needed to keep a linear history before pushing to svn.

If that statement is incorrect, I'd appreciate to understand why.
