### ISSUE TITLE
你这HTML 完全手写还是什么工具

### ISSUE THREAD

**Issue by atzouhua** [git/git-reference#109]
rt

**Comment by brntbeer** [comment]
hey @zouhua! i'm going to go ahead and close down. Not sure if you're asking about the HTML being generated or user contributed. Let me know and I'm happy to re-open this

**Comment by atzouhua** [comment]
yes

**Comment by brntbeer** [comment]
@zouhua it's completely user contributed and hand written actually!

if there's any contribution you want to make, please do so. I'll be sure to review it and get some extra eyes on it to get it approved and merged in.
