### ISSUE TITLE
Git Bash Command Line Drag & Drop Option

### ISSUE THREAD

**Issue by ghost** [git/git-reference#115]
Hello. I used to drag and drop folders to Git Bash command line to change the working directory or to create new repos, but this option is no longer available. I'm using Windows 10 64bit - Any clues about this issue? Thank you.

**Comment by brntbeer** [comment]
@edherroj hi 👋 ! This repo is more suited for learning about Git itself and not the program that runs the command line interface for windows. Let me see about getting you some help here anyways!

stay tuned

**Comment by brntbeer** [comment]
@edherroj if i would have waited 2 more minutes it looks like i would have had an answer 😆 

If you head over to https://github.com/git-for-windows/git, that looks like the best place to ask this question. The Git Bash project itself is contained inside of git for windows, and so there are issues over there that also involve git bash.

I'm going to close this out, feel free to still comment here if something's unclear ❤️ :octocat:

**Comment by ghost** [comment]
@brntbeer thank you for your answer. I'll take a look at that info.

- Ed
