### ISSUE TITLE
Public git changelog

### ISSUE THREAD

**Issue by mohsin** [git/git-reference#119]
I'm looking for a list of major changes made to git over the years but I can't find any. Even the main repo doesn't seem to have a changelog file or a wiki to refer this. The main reason is that I want to know what major changes have been made since the release of Pro Git book (which is now 4 years old).

**Comment by dscho** [comment]
> I'm looking for a list of major changes made to git over the years but I can't find any.

Look here: https://github.com/git/git/tree/master/Documentation/RelNotes

**Comment by mohsin** [comment]
Thanks @dscho
