### ISSUE TITLE
Missing documents for `git subtree`

### ISSUE THREAD

**Issue by DevDengChao** [git/git-reference#123]
Current situation:
`git subtree --help` open up local documents currectly.
While `https://git-scm.com/docs/git-subtree` is redirected to `https://git-scm.com/docs`

Expected:
Amend git subtree's online document.

**Comment by rimrul** [comment]
The repository for issues with git-scm.com is [git/git-scm.com](https://github.com/git/git-scm.com).

But that aside, I think the main reason why the documentation for `git subtree` is not available on git-scm.com is that it lives in `contrib/subtree` and not in `Documentation`.

**Comment by DevDengChao** [comment]
@rimrul thanks.
