### ISSUE TITLE
Two invocations of "git reset" not mentioned

### ISSUE THREAD

**Issue by dcecile** [git/git-reference#20]
At http://gitref.org/basic/#reset the author is talking about the complexity of `git reset` and says, "I'll just tell you the three specific invocations of it..." In the reference manual, only `git reset HEAD` is used; the remaining two of three invocations are missing.

**Comment by matthewmccullough** [comment]
I think this should either link to or re-use some Three Trees content from @schacon.
- http://www.infoq.com/presentations/A-Tale-of-Three-Trees
- https://speakerdeck.com/u/schacon/p/a-tale-of-three-trees
- http://git-scm.com/2011/07/11/reset.html
