### ISSUE TITLE
Possible Spelling Error

### ISSUE THREAD

**Issue by nesparza** [git/git-reference#3]
On the page: http://gitref.org/remotes/

First line of the heading: git remote, reads "Unline centralized version control systems that have..."  Maybe 'unline' should be 'unlike'?

Thank you so much for posting this tutorial. It was extremely useful for me getting "ramped up" on using GIT

**Comment by ComputerDruid** [comment]
this appears to have been fixed by e4cd83ea7138b74e7502b9cfd58e55cfaf7107f7

**Comment by nesparza** [comment]
looks good
