### ISSUE TITLE
stash and revert

### ISSUE THREAD

**Issue by JayStar42** [git/git-reference#36]
please add git stash and git revert

**Comment by randomecho** [comment]
Any ideas on where `git revert` would fall under on the topics?

Doesn't feel like a basic snapshot type of lesson to learn as it can get messy rather quickly.

And if we based things sort of along the lines of [Git SCM](http://git-scm.com/book/commands), it's not even listed there.

**Comment by matthewmccullough** [comment]
Would have to think about where it fits, but thinking about how to structure it as a "short lesson," what do you think about this (have used this in the classroom):
- Most coding is forward moving.
- Git allows craftsmen and craftswomen to think about making the history beautiful, not just the "end state."
- When you create more handsome intermediate states, it is easier to roll back.
- Git revert surgically inverts an old (bad) commit with a new one at the end of the timeline. This is like a banking transaction where you write a new ledger entry that apologizes for the mistake, not erasing the old incorrect ledger entry.

**Comment by randomecho** [comment]
Squashing commits also play into making a beautiful history. You can have a dozen incremental commits all neatly rolled into one umbrella.

Liking the bank ledger analogy. If people forget what ledgers are you could also reference credit card chargebacks.

**Comment by matthewmccullough** [comment]
Having thought about this, it almost a warrants a separate section on the left nav. "Shaping history"

?

**Comment by randomecho** [comment]
Agreed. Though, thought that's where you were heading in anyway when thinking about making a lesson of it.

**Comment by matthewmccullough** [comment]
@randomecho Ah. The lesson isn't for the this, but rather for a slide deck for our training services via http://training.github.com (but will be open source). Was just noting what was working for me in the classroom.

**Comment by alasheevayuliya** [comment]
No sharing

**Comment by brntbeer** [comment]
Stash and revert are covered in our training kit at https://training.github.com/kit/intermediate and https://training.github.com/kit/advanced
