### ISSUE TITLE
Change all Progit.org links to git-scm.com/book links

### ISSUE THREAD

**Issue by matthewmccullough** [git/git-reference#42]
ProGit.org content was folded into git-scm.com/book

**Comment by randomecho** [comment]
Sorry, should have checked to make sure it wasn't already assigned.

**Comment by leto** [comment]
Is there still work that needs to be done here or is this closeable?

**Comment by randomecho** [comment]
Should be good and dusted. Couldn't find any lingering progit.org links on a quick search.

**Comment by tlberglund** [comment]
Lots of git-scm.com, no progit.org anywhere to be seen. Closing.
