### ISSUE TITLE
How can I clone this docs and put them in my site?

### ISSUE THREAD

**Issue by tankywoo** [git/git-reference#61]
1. I saw the index.html have a `layout: reference`
2. the _layouts/reference.html have `{{ content }}`, I think the content such as index.html should be put in this block

But I don't know how can I use it ? Just put the _layouts/reference.html to index.html by hand?

And all the static files such as css/js ... all use absolute path. And I think it should be relative path if the directory is sub directory

**Comment by brntbeer** [comment]
Unfortunately this site needs some work. As it stands right now it needs to be turned into a jekyll site to be more like https://github.com/github/teach.github.com, https://github.com/github/training.github.com, and https://github.com/github/learn.github.com.

Are you looking to have the docs just embedded on your site? Maybe just a link to a given page may work best? 

I'd be more than happy to continue to help if you walk me through the use-case you're wanting! :)

**Comment by goofyft** [comment]
i'm looking at just running it locally on my box so that i don't have to be connected to browse it.

**Comment by matthewmccullough** [comment]
@goofyft All you have to do is run `jekyll` on them and it emits filled-in HTML.  @github/training-team correct me if I'm wrong here.

Reference: http://jekyllrb.com

**Comment by brntbeer** [comment]
Nailed it! correct.

If Jekyll isnt installed, just type `gem install jekyll`

Also, to get things up and running, you have to type `jekyll --server` to start serving the content on your computer. Doing so will allow you to open a browser and go to the address of `localhost:4000` to start seeing the content
