### ISSUE TITLE
Make the left navigation bar stay in view

### ISSUE THREAD

**Issue by janpipek** [git/git-reference#62]
I think that it would be nice to have the left menu visible all the time because one usually skips from one link to another (reads more of them) and for that you have to jump back to the beginning of the page. There is enough unused horizontal space for that.

Take it just as an idea. Otherwise, I like the page and it is helpful even in its current form.
Thank you,
Jan

**Comment by brntbeer** [comment]
Glad to hear this site is helpful!

Work on this site isn't really too active, so perhaps you (or someone else in the community?) could put that PR in. 

I was also curious if you've seen http://git-scm.com/documentation, which contains the same material and is more up to date

**Comment by janpipek** [comment]
Your site is fine because it is short a simple enough to be of practical use (without lots of visual stuff :-)). I know about the other too, of course :-)

Nevermind, if the site is not much active, it probably is not worth the effort to improve it.
Cheers,
Jan
