### ISSUE TITLE
git reset HEAD doesn't undo the last commit

### ISSUE THREAD

**Issue by ugtar** [git/git-reference#63]
The docs for git reset say:
'git reset HEAD undo the last commit and unstage the files'

git reset HEAD will unstage files, but it will not undo the last commit unless you reset HEAD to HEAD~1 or HEAD^.

the sections for `git reset --soft` and `git reset --hard` also say the last commit will be undone.

I think this needs to be clarified.  Thanks

**Comment by matthewmccullough** [comment]
@github/training-team Check me here from my late night reply GMT time, but any reset to HEAD is to _current state_, not any previous state, just as @ugtar noted.

**Comment by jordanmccullough** [comment]
:100: from my assessment as well. In short, yes @matthewmccullough and @ugtar, that needs to be fixed.

**Comment by randomecho** [comment]
As the one who wrote that bit in after reading through the docs, don't remember how that mistake was made.
