### ISSUE TITLE
git stash doesn't stash away unversioned files

### ISSUE THREAD

**Issue by gergelypolonkai** [git/git-reference#68]
You should mention that `git stash` doesn't stash away files that are not in the index yet. It can cause much trouble if you e.g. do a git clean -dfx on the super-urgent-bugfix branch. However, 1.7.7 and up has `git stash -u` to do this.

**Comment by matthewmccullough** [comment]
@gergelypolonkai That's a point that could indeed be helpful to some readers. Could you submit a pull request with some potential changes and we can iterate with you from there?

**Comment by tlberglund** [comment]
Closing due to PR in progress. Thanks for starting this, @gergelypolonkai. :smile:
