### ISSUE TITLE
Typo on front page

### ISSUE THREAD

**Issue by bfoz** [git/git-reference#7]
The last sentence of the first paragraph should say "present" instead of "preset"...

"The commands are organized into sections of the type of operation you may be trying to do, and will preset the common options and commands needed to accomplish these common tasks."

**Comment by ComputerDruid** [comment]
this appears to be fixed

**Comment by matthewmccullough** [comment]
Thanks for the contribution. The @github/training-team and I have taken the maintenance of this over so we'll be reviewing issues frequently now. We appreciate your efforts.
