### ISSUE TITLE
Collapse gitref.org site content into training.github.com

### ISSUE THREAD

**Issue by matthewmccullough** [git/git-reference#72]
Like https://github.com/github/learn.github.com/issues/52 perhaps we should merge all this site's content into training.github.com too.  We may have lost the domain name in #71 but we can save the content and make a commit that empties this repo the same way @jordanmccullough [did for learn.github.com](https://github.com/github/training.github.com/pull/147) and teach.github.com.

**Comment by jordanmccullough** [comment]
As much as I :heart: keeping credit where credit is due (by means of `commit`s), I'm concerned that merging in this content would make the root of the training.github.com project messier than it already is.

Would it make more sense for the Training Team to review the resources here and carefully select (`cherry-pick`) those that remain of value?

**Comment by randomecho** [comment]
Can't most, if not all, of the content here be found in git-scm.com, GitHub:Halp and the slides?

**Comment by matthewmccullough** [comment]
@randomecho I think so, but I loved its bite-sized chunks, which I think are somewhat unique.

**Comment by afeld** [comment]
- The migration: https://github.com/github/training.github.com/pull/154
- My proposed alternative: https://github.com/github/gitscm-next/issues/332

Mind if we close this so as to not further dilute?

**Comment by brntbeer** [comment]
Do it

On Wednesday, December 11, 2013, Aidan Feldman wrote:

> - The migration: github/training.github.com#154https://github.com/github/training.github.com/pull/154
> - My proposed alternative: github/gitscm-next#332https://github.com/github/gitscm-next/issues/332
> 
> Mind if we close this so as to not further dilute?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/git-reference/issues/72#issuecomment-30303647
> .

## 

Brent Beer
GitHub Training
http://training.github.com
https://github.com/brntbeer
