### ISSUE TITLE
Subsection Anchors 

### ISSUE THREAD

**Issue by simeonwillbanks** [git/git-reference#74]
The other day, I tired linking `git log -S`, but I couldn't.  I had to link [`git log`](http://gitref.org/inspect/#log).  May I add subsection anchors?

![h4-anchor](https://f.cloud.github.com/assets/164506/1882507/0f48bbb2-7977-11e3-8307-1ed6c6af85d6.png)

``` html
<h4>
  git log -S
  <small>filter by introduced diff</small>
  <a name="log-s"></a>
</h4>
```

Thoughts?  Thanks!

**Comment by matthewmccullough** [comment]
> May I add subsection anchors?

Please do. That would be very helpful.

**Comment by simeonwillbanks** [comment]
Sounds good.  :smile:
