### ISSUE TITLE
Translating Git

### ISSUE THREAD

**Issue by ziyaddin** [git/git-reference#78]
Hi, is there any chance to translate Git-scm and Git itself to different languages? Thanks!

**Comment by randomecho** [comment]
For Git-SCM at least you can read about how some part of it has been started/raised: https://github.com/git/git-scm.com/issues/265

**Comment by ziyaddin** [comment]
So, can we do it? ( I didn't get it, can we or not, sorry ). I understand that it is difficult, yeah? Thanks!

**Comment by randomecho** [comment]
If you want to work on a pull request that makes it easier to get Git-SCM translated, go for it.

Right now it looks like it's not yet making use of the config/locales, but it's ready for work to be done on it.

**Comment by ziyaddin** [comment]
Thanks @randomecho for your answer!
