### ISSUE TITLE
git remote typo

### ISSUE THREAD

**Issue by fonnesbeck** [git/git-reference#8]
First sentence:

"Unline centralized version control systems that have a client that is very different from a server ..."

should read "Unlike centralized version control ...", I think.

**Comment by ComputerDruid** [comment]
this seems to have been fixed by e4cd83ea7138b74e7502b9cfd58e55cfaf7107f7

**Comment by matthewmccullough** [comment]
Thanks for the contribution. The @github/training-team and I have taken the maintenance of this over so we'll be reviewing issues frequently now. We appreciate your efforts.
