### ISSUE TITLE
Repeated url in the description of this Repository

### ISSUE THREAD

**Issue by dhanvi** [git/git-reference#89]
In the description of the repository the website http://gitref.org is mentioned twice 
![screenshot from 2015-03-30 23 04 51](https://cloud.githubusercontent.com/assets/6671379/6902414/56c561ac-d731-11e4-86c4-a2d7b547d9c8.png)

**Comment by randomecho** [comment]
That's a result of making the first part, the description, include the URL in the repo summary. If you removed that part and made it reference the URL field, then when it displays on [the organisation's list of repos](https://github.com/github), you will only see

> **git-reference**
> Online Git Reference at

**Comment by brntbeer** [comment]
I went ahead and removed the website field from the repository description so that this would look better when you view the repository home page, and when viewing from the Orgs repo list.
